### ISSUE TITLE
Start: Enterprise Super App Platform (ref: WeChat, Grab)

### ISSUE THREAD

**Issue by p-raj** [p-raj/reads#12]
Super App for the Enterprises where the IT could ship instant apps across the organization fast and enable a bottom-up approach in app development in the organization.

**Todo**

- [x] Define problem statement & solution
- [x] Define market & similar competition
- [x] Define product & probably the UI
  - [x] MVP
  - [x] Long term
- [x] Target audience
- [ ] Fill in business canvas
- [x] Pitch deck
  - Introduction
  - Team <if you have a great team - 2nd slide otherwise 2nd last slide>
  - Problem Statement
  - Solution
  - Market Size
      -Target Market
  - KPIs <if there are any>
  - Business Model Opportunities
  - Competition
  - GTM
  - Vision & Mission
  - Roadmap

**Comment by p-raj** [comment]
# Problem Statement

- [Low Talent Supply v/s Demand - StackOverflow](https://insights.stackoverflow.com/survey/2017#developer-roles)
- [High cost of developing and maintaining an application](http://www.formotus.com/14018/blog-mobility/figuring-the-costs-of-custom-mobile-business-app-development)
    - Average time taken for first launch - 7 Months
    - Average cost in the range of - 110,000$ to 305,000$ 
    - Average updates per annum - 3
- [Demand for mobile apps will grow 5X faster than internal IT organizations' capacity to deliver them - Gartner](http://www.gartner.com/newsroom/id/3076817)
- Apps used in an Enterprise > 300
    - Of the used apps, available on mobile ~ 17
- Bad UX for the web-apps extended to the mobile - general trend in the Enterprise
- No consistent UI/UX across the apps
- IT integration hell
    - Sec Ops
    - Dev Ops
    - Authorizations
    - SSO
    - All of the above and more - for web-app, for API, for mobile-app, for hosting server - as many interfaces the vendor is offering
    - Data integration hell
    - High barrier to entry for the innovative startups/solutions

Enterprises are still playing catchup in the mobile transformation and when it does (if it does) the market would move to more intuitive and productive interface.

SaaS has been transformative for the Enterprises, it changed the way decisions used to be made, from tops-down to bottoms-up, now every team uses it's own preferred set of tools, even for the same business process - eg: project management, eg: issue management. Results - 
- The backlog for the IT teams is continuously on a rise
- budgets are strained
- CIOs can either dedicate resources to improve productivity or to keep up with the market
- Denying the team of an opportunity to pick and choose their own tools hurts the productivity

Feels like a death spiral.

# Solution

A platform that can integrate with any data source or service, further provides and ability to the IT to create a business process and map the business process to a library of UI elements to build an app and ship multiple apps to the end users.
The end users would be having a super-app platform running on their mobile phone (might be integrated with the enterprise SSO, or if the entperprise wants to extend this to outside the organizations with - email, password) that can receive a new business app instantly.

**Comment by p-raj** [comment]
# Market
<img width="1018" alt="screen shot 2018-08-24 at 4 53 46 pm" src="https://user-images.githubusercontent.com/40564263/44582165-4d75f100-a7be-11e8-8822-8f628fc75be8.png">

**Comment by p-raj** [comment]
# Concept Details

[Apps-V_3.pdf](https://github.com/p-raj/xyz/files/2318135/Apps-V_3.pdf)

**Comment by p-raj** [comment]
# User Interface Design

[DEMO (ok)] https://www.youtube.com/watch?v=HfZT75rduPg

# Detailed Concept Note

<img width="1000" alt="screen shot 2018-08-24 at 5 05 52 pm" src="https://user-images.githubusercontent.com/40564263/44582742-40f29800-a7c0-11e8-8436-f3ef41e922b2.png">
<img width="1000" alt="screen shot 2018-08-24 at 5 06 01 pm" src="https://user-images.githubusercontent.com/40564263/44582743-40f29800-a7c0-11e8-894f-c6a7a3b7015c.png">
<img width="1000" alt="screen shot 2018-08-24 at 5 06 09 pm" src="https://user-images.githubusercontent.com/40564263/44582744-40f29800-a7c0-11e8-9f57-0f69e6627de8.png">
<img width="1000" alt="screen shot 2018-08-24 at 5 06 20 pm" src="https://user-images.githubusercontent.com/40564263/44582745-418b2e80-a7c0-11e8-953e-6ca8733bd4af.png">
<img width="1000" alt="screen shot 2018-08-24 at 5 06 26 pm" src="https://user-images.githubusercontent.com/40564263/44582746-418b2e80-a7c0-11e8-9544-8f96932103ba.png">
<img width="1000" alt="screen shot 2018-08-24 at 5 06 30 pm" src="https://user-images.githubusercontent.com/40564263/44582747-418b2e80-a7c0-11e8-98d5-b198590c9994.png">
<img width="1000" alt="screen shot 2018-08-24 at 5 06 39 pm" src="https://user-images.githubusercontent.com/40564263/44582748-4223c500-a7c0-11e8-8636-37c75b2c9e27.png">
<img width="1000" alt="screen shot 2018-08-24 at 5 06 44 pm" src="https://user-images.githubusercontent.com/40564263/44582749-4223c500-a7c0-11e8-85a8-cb78e227023b.png">
<img width="1000" alt="screen shot 2018-08-24 at 5 06 48 pm" src="https://user-images.githubusercontent.com/40564263/44582753-4223c500-a7c0-11e8-81a0-d93a35906796.png">
<img width="1000" alt="screen shot 2018-08-24 at 5 06 56 pm" src="https://user-images.githubusercontent.com/40564263/44582754-42bc5b80-a7c0-11e8-8966-16e83111248d.png">
<img width="1000" alt="screen shot 2018-08-24 at 5 07 02 pm" src="https://user-images.githubusercontent.com/40564263/44582756-42bc5b80-a7c0-11e8-9a30-0c7543f9c33a.png">
<img width="1000" alt="screen shot 2018-08-24 at 5 07 31 pm" src="https://user-images.githubusercontent.com/40564263/44582758-42bc5b80-a7c0-11e8-9c7a-ff355d201ce6.png">
<img width="1000" alt="screen shot 2018-08-24 at 5 07 35 pm" src="https://user-images.githubusercontent.com/40564263/44582759-42bc5b80-a7c0-11e8-88e7-73eb0dd4ccb2.png">

### PDF - [Apps-V_3.pdf](https://github.com/p-raj/xyz/files/2318139/Apps-V_3.pdf)

# Pre-Alpha release 
[Umbrella Repository for Alpha Release](https://github.com/veris-pr/v3)

**Comment by p-raj** [comment]
# [Umbrella Repository for Alpha Release] (https://github.com/veris-pr/v3)

**Comment by p-raj** [comment]
# Great References 

1. https://techcrunch.com/2018/08/16/work-bench-enterprise-report-predicts-end-of-saas-could-be-coming/
1. https://www.scribd.com/document/386310309/2018-Work-Bench-Enterprise-Almanac 
1. https://www.youtube.com/watch?v=iu5hTMlTU-U
1. https://www.youtube.com/watch?v=b-RS5vpS_0s
1. https://twitter.com/conniechan?lang=en
1. https://www.youtube.com/watch?v=xd5EoVc3I_Y
1. https://techcrunch.com/2018/03/21/microsoft-power-apps-update-includes-new-common-data-service/
1. https://techcrunch.com/2018/03/13/supernova-studio/
1. https://techcrunch.com/2017/05/17/forest-is-the-administration-interface-to-rule-them-all/
1. https://blog.airtable.com/introducing-airtable-blocks/

# Directly Relatable

<img width="800" alt="screen shot 2018-08-24 at 5 17 58 pm" src="https://user-images.githubusercontent.com/40564263/44583228-ef4b0d00-a7c1-11e8-9957-4926dfcf97e6.png">
<img width="800" alt="screen shot 2018-08-24 at 5 18 21 pm" src="https://user-images.githubusercontent.com/40564263/44583229-ef4b0d00-a7c1-11e8-9366-cea810be5066.png">
<img width="800" alt="screen shot 2018-08-24 at 5 18 36 pm" src="https://user-images.githubusercontent.com/40564263/44583230-efe3a380-a7c1-11e8-89d8-757d4bffc010.png">
<img width="800" alt="screen shot 2018-08-24 at 5 18 53 pm" src="https://user-images.githubusercontent.com/40564263/44583231-efe3a380-a7c1-11e8-999e-457fc2bdf5f1.png">
<img width="800" alt="screen shot 2018-08-24 at 5 19 33 pm" src="https://user-images.githubusercontent.com/40564263/44583232-efe3a380-a7c1-11e8-88df-b1e0af8f374b.png">

# Points takes from the Enterprise Almanac 2018

- Deep IP Software companies are difficult - easy for AMZ to Host Open Source S/W and extend as service.
- Good AI use-case : AI enabled Business Process Transformation 
- S/W interface as invisible as possible (every time a user comes to complete a task, help complete the task faster)
    - collate data
    - understand context
- Data -> (Domain Expert + AI) -> User Interface -> More Data
- Invisible Apps - automate a business process using existing SaaS
- Vertical AI - improve organization performance using internal data
- Data -> Information -> KPI -> *<< ACTION >>*
- Containers are posing a challenge to SaaS - easy of developing and deploying apps is making the organizations to incline towards "build"
- [strategy] AI - go with a business case, start with existing data
- [strategy] - middleware to map process and automate -> extract insights
- [strategy] - consumer like UI in Enterprise grade software
- [strategy] - undercut the cost with non-linear growth in cost to customer
- [strategy] - go bottom-up
- [strategy] - cross-domain business information -> accessible to everyone within the org: collaboration + (information/ task) distribution = productivity
- [strategy] - buy --> build is the new mind set
- [strategy] - cloud < multi-cloud < VPC: preference 
- [strategy] - old problems + new go to market
- [strategy] - be integration ready on the terms of Enterprise, don't make the enterprise IT put in effort
- [strategy] - multiple users would have multiple personalities, modify the offering accordingly
- [strategy] - auto-organize the data in multiple clusters, thus helping the use understand data better without the use of Data Analyst
- [strategy] - think about 1 click everything (build, deploy, distribute, scale)
- [strategy] - Data -> Information -> 100 KPI -> 10 KPI -> 1 KPI -> **Action**
- [strategy] - Enable citizen data scientist to help organizations - organizations still keep the full control over data - data shared is anonymized - **Opportunity** - instead of KAGGLE as a central organizing platform - KAGGLE hosted for every organization - built-in data governance tools
- Easy SaaS customization + Easy integration + Easy reports/KPI => Suggest actions & track outcomes
