### ISSUE TITLE
Start: Complete Discussion Platform for - Idea, Startup, Execution & MVP

### ISSUE THREAD

**Issue by p-raj** [p-raj/reads#6]
Like - https://code4startup.com (Learn to code by creating Real life Startups), but for the business side of things.

**Todo**

- [x] Define problem statement & solution
- [x] Define market & similar competition
- [ ] Define product & probably the UI
  - [x] MVP
  - [x] Long term vision
- [x] Target audience
- [ ] Fill in business canvas
- Pitch deck
  - Introduction
  - Team <if you have a great team - 2nd slide otherwise 2nd last slide>
  - Problem Statement
  - Solution
  - Market Size
      -Target Market
  - KPIs <if there are any>
  - Business Model Opportunities
  - Competition
  - GTM
  - Vision & Mission
  - Roadmap

**Comment by p-raj** [comment]
# Problem Statement (short)

There are a lot of forums to share ideas, discuss ideas, get feedback on ideas, learn from ideas, but there exists none to discuss and learn from execution of the successful companies.

# Solution (short)

A simple website - similar to https://code4startup.com (Learn to code by creating Real life Startups) - where people can gather all the information related to execution of successful and failed startups and discuss how would they go about executing the same idea (eg: how would you go about executing Uber?)

Ultimately the plan is to get an extended historical timelines of challenges and decisions made by the successful companies vs unsuccessful ones, ultimately helping entrepreneurs become better at building companies/ products.

# Problem Statement (extended)

1. Content to learn about any startup's execution (successful startup or a failed) and startup's evolution is not available at a common place.
1. Challenges in execution in different environment is discussed in some business blogs, again not available at a common place.
1. Existing discussion forums are too generic for a business related discussion. The forums need to evolve and include more tools specific to business execution.
1. Similar to `Coding bootcamps`, learn by doing is missing.
1. Data is unstructured.

# Solution (extended)

1. Collect resources, stories etc about the startups and companies riding on rising tide, present the execution and strategies in a well defined data & presentation format. Keep the resources upto date.
1. People can ask about particular things in the execution strategy of a company and provide their own feedback on why it would be a hit or why it would fail.
1. People can learn and share their mental models
1. People can define their own strategies for execution and share with the community, a startup can be built in a thousand ways.
1. Evolve forums to a debate platform, rather than just an infinite stream of comments.
1. Business specific components for discussing the
    1. MVP
    1. https://strategyzer.com/canvas/business-model-canvas - Business Model Canvas
    1. product wireframe designs
    1. Value chain diagram and discussion about how it might shift
1. Discuss challenges and solutions
1. Discuss potential futures, features, possibilities
1. Ask for data around any problem, market, solution
1. Collaborate on the execution plan, merge problems and solutions
1. Stackoverflow like community driven
1. Share self biases and expert opinion
1. attach research links and discuss
1. proper highlighting and commenting like Medium
1. Short, 140 char limit on the discussion points, followed by possibility of an extended version.

**Comment by p-raj** [comment]
#  Define market & similar competition (short)

There are a lot of `Startup Discussion Forums`, `Founder Communities`, `Startup Communities`, these sites provide generic discussion forum, stackoverflow like Q&A, reddit like discussion threads.
Further there are a lot of `Idea Sharing`, `Co-founder Search`, `List Startups`, `Launch Startups`, but these sites lack a proper discussion forum.
This platform lies somewhere in-between, where there exists a list of existing startups, company data, company timeline and execution strategy/plan. Users can similarly define their own `execution plan`, and on that collect a feedback from the community.
Execution is an important part of the business, users should also be able to find the Failed Execution Plans, pivot, failed companies and reason for failure.
This site would list existing business and probably in the future problem discussion platform.

# Inspiration

### Company Page

**Company Timeline** - displaying the company phases, the decisions, execution strategy, executive team expansion, company size

eg: Problem -> MVP -> Test & Iterate/ Pivote -> Market Fit -> Growth & challenges -> Executive Team

1. http://usblogs.pwc.com/emerging-technology/robotics-and-ai-interactive-timeline/
1. https://in.pinterest.com/pin/270427152606757915/
1. https://venngage.com/blog/timeline-template/

**Company Info** 

1. Crunchbase Data
1. Bloomberg 
1. CBInsights

**Business Model**

1. Probable sample business canvas and discussion
1. Eco-system map (eg: for Uber - Car Companies, Insurance, Taxi, Driver, Customer, City, etc)

**Links to Various Thesis for the Company & Execution Strategies**

1. https://stratechery.com/2018/more-spotify-spotify-uber-and-airbnb-uber-waymo-and-softbank/
1. https://readwrite.com/2017/02/17/why-many-major-american-companies-have-struggled-in-china-uber-il1/

# Target audience

Entrepreneurs, industry experts, product managers.
1. Entrepreneurs would be interested in validating assumptions, check similar problems and possible solutions.
1. Industry experts would be interested in providing the feedback, and possibly get in touch with the people trying to built it right.
1. Product managers would be interested in gathering ideas about product growth strategies. 

# Possible monetization plan

1. Newsletter subscription 
1. Private listing for self-startup

**Comment by p-raj** [comment]
# Define product & probably the UI

**TODO**: UI

## MVP

- List of a few news-worthy startups (to begin with). Eg: Uber, Lyft, AirBNB. Try to gather startups with some commonality, eg: on-demand, saas, etc.
- Build a timeline of the company
    - Short timeline - idea, founders, launch, funding, scaling, etc
    - Long timeline - frame by frame dwelling into the short timeline items and adding more items (eg: articles by analysts on some decision, articles on analyst on how it was built and why it succeeded, critical analysis of the decisions made, controversies etc) - basically wikipedia with a timeline for the company
- Links to the founder profiles
- Founder Timelines
    - Short timelines - eg: https://www.cnet.com/news/steve-jobs-a-timeline/
    - Extended timelines 

## Long term version

- Add product timelines
- Add the people worked in the company timelines (people would share their own stories ad they recall) - gather the data around people who helped build the company

The ultimate database for a company's history before it gets lost or gets chunked into a bunch of tags and quotes.

- Market timelines - automatically draw from the data around multiple companies that helped build the market & wave.
