### ISSUE TITLE
Start: DAO (Decentralized autonomous organization) Platform for a SAAS Company

### ISSUE THREAD

**Issue by p-raj** [p-raj/reads#7]
Auto-executing Contract platform for SAAS companies.

**To Study**

- [x] How contracts work? ETH (others?)
- [x] How would contracts be used in the platform?
- [x] Why they are a good idea/ or/ a bad idea?

**Todo**

- [x] Define problem statement & solution
- [x] Define market & similar competition
- [ ] Define product & probably the UI
  - [ ] MVP
  - [ ] Long term
- [ ] Target audience
- [ ] **White-paper**
- [ ] Fill in business canvas
- [ ] Pitch deck
  - Introduction
  - Team <if you have a great team - 2nd slide otherwise 2nd last slide>
  - Problem Statement
  - Solution
  - Market Size
  - Target Market
  - KPIs <if there are any>
  - Business Model Opportunities
  - Competition
  - GTM
  - Vision & Mission
  - Roadmap

# Initial Idea

![img_3640](https://user-images.githubusercontent.com/40564263/43368472-2844ab4e-937b-11e8-8896-df60885b16bd.jpg)

**Comment by p-raj** [comment]
# Problem Statement

Primary reason for the existence of a Company is to serve their Customers, to help their Customer get to where they want to go, faster. Eg: Customer - Data Science & Analytics organization, Vendor Company - Data cleaning and munging platform (or data tagging platform), because the Customer wants to focus on their primary agenda - serving their own customers.
A single company would be serving multiple customers with multiple product versions, or build specific features for their customer, or have multiple disparate products or separate products, and hence have multiple teams to manage the portfolio. As the company grows, so does its offerings.
But, growing up brings its own set of challenges
- finance management
- roadmap planning and management
- ego clashes, politics, bad management
- how to prioritize on what products/features/projects would get attention and funding and what products/features/projects won't
- best ideas doesn't always win
- not everyone works to make things happen, make the company work
- hierarchies make it hard for everyone to get heard and contribute their best
- operations/ processes become data driven and gut is forgotten
- no single person - CEO, CXO, VP, product manager - can make all the right decisions
- best person to sale product, market product, manage product, develop product, define dev-ops, etc is not in company
And then, what about compensating the the open-source technology's authors, the libraries used in the project.
A lot of things that made "The Startup" in a "Great Company" gets lost along the way, the key element - **Trust - in the whole eco-system gets weak**

# Solution

[DAO](https://en.wikipedia.org/wiki/Decentralized_autonomous_organization) is a great idea.
Actors in a typical SaaS company or in a SaaS company's eco-system - 
- Customer
- Sales
- Marketing
- Product
- Engineering
- Operations
    - Support 
    - DevOps 
    - General Ops
    - Supply chain
- 3rd party vendors (eg: Plivo) & partners (eg: SAP)
- Consultants
- Open Source software developers

DAO brings in a new way to think about the company & the actors involved, auto-executing contract based partnership, where in the company get to try a lot of ideas simultaneously and the actors get a change to optimize their earnings (or whatever the contract states). 
Eg: 
<Company: SaaS>
- <Actor: Sales> <Location: Global, Remote> 
    - <Contract: per 10 licenses sold would get 1% of Sales Quote>
- <Actor: Marketing> <Location: Global, Remote> 
    - <Contract: per 10 conversion get 1% of sold item value>
- <Actor: Engineering> <Location: Global, Remote> 
    - <Contract: get 100$ per feature per hour>
        - <Actor: OS Dev> <Contract: get 1$ per library used in the project>
- <Actor: Customer>
    - <Contract: pay 100$ less for any outage>
    - <Contract: earn 100$ for sharing data & co-owining>

This ensures that every Actor has their skin in the game, can optimize their earning, can contribute in making the world a better place (usually the company's vision/mission), and gets paid automatically on the basis of the contract
- The best people get to work with the company, risk free
- The best ideas get to see the daylight
- The company remains the disruptor
**The Trust in the eco-system is maintained.**

<img width="502" alt="screen shot 2018-07-31 at 6 25 48 pm" src="https://user-images.githubusercontent.com/40564263/43460774-3dd70644-94ef-11e8-8a57-034d59546561.png">

**Comment by p-raj** [comment]
# How contracts work? ETH (others?)

- http://whatthefuckisethereum.com/?ref=producthunt#nerd
- https://docs.google.com/document/d/1ejYCWkHQIRInXB4VifoHevom8CWVJ69zFVfP4J2fjSU/edit#
- https://novicedock.com/learn/cryptocurrency/ethereum/introduction-10
- https://github.com/ethereum/wiki/wiki/White-Paper#introduction-to-bitcoin-and-existing-concepts
- https://medium.com/@preethikasireddy/how-does-ethereum-work-anyway-22d1df506369
- https://medium.com/@preethikasireddy/fundamental-challenges-with-public-blockchains-253c800e9428

**Comment by p-raj** [comment]
There has been a lot of work done on the DAO & smart-contracts, so the idea I thought upon seems like a common knowledge in the industry (https://medium.com/practical-blockchain/decentralized-autonomous-organizations-overview-2e752e194c5b)

**Similar Platform**
- https://colony.io
- https://aragon.org
All the best to these companies.

I believe there DAO are the way of the future, where everyone could be anyone and not just a list of tags defined by their job, where everyone would be able to work on anything they are curious about, as long as they are curious about, bound-free and able to get in any exciting opportunity from day-1. 
This is what the next generations of companies would look like and should look like.

**Challenges (in my view)**

- The notion of privacy needs to change (in the minds of the partners - company, actors etc)
    - around money
    - around the job
    - a lot of systems need to come online (pen & paper is still the way many industries work)
    - companies comfortable in sharing their KPI's (this would determine the "job well done" part)

Technical issues would be resolved, but societal issues are the real challenge. This would be an amazing idea after 15(-to 20) years, for sure.
