### ISSUE TITLE
Start: AR (augmented reality) App for better informed shopping decisions

### ISSUE THREAD

**Issue by p-raj** [p-raj/reads#9]
AR app for the customers to make more informed decisions about the products they want to purchase.

**Todo**

- [x] Define problem statement & solution
- [x] Define market & similar competition
- [ ] Define product & probably the UI
  - [ ] MVP
  - [ ] Long term
- [x] Target audience
- [x] Fill in business canvas
- [ ] Pitch deck
  - Introduction
  - Team <if you have a great team - 2nd slide otherwise 2nd last slide>
  - Problem Statement
  - Solution
  - Market Size
      -Target Market
  - KPIs <if there are any>
  - Business Model Opportunities
  - Competition
  - GTM
  - Vision & Mission
  - Roadmap

**Comment by p-raj** [comment]
# Problem

Usually the customers stick to the brand or the product they know how to use or have been using it since a long time, they generally ignore equally good products from similar brands or some new company. It's quite a monotonous experience for the customers - walk in, pick up the products you already use, walk out, the end.
Sometimes the customers do like to try something new, either they have been suggested by their friends or just to change a few things or to solve some very specific problem or just to try something new, and here comes the problem of lack of information about 
- how to use the product?
- what are product reviews?
- available cheaper somewhere else?
- how effectively does it solve the problem ?
- how does the alternatives compare?

If only the customers would be able to get all the information they would like to see, that would help redefine the shopping experience and people might again get interested in trying new brands and products.

# Solution

AR app, in which user would be able to put in `various tasks` that they would want to achieve or their `general shopping list`, example

**task list** 
- to fix the vacuum cleaner bag
    - as seen on - <some site>
- to cook a vanilla cake 
    - personal recipe
    - as seen on - <some site>

**specialized shopping list**
- fruits
    - special requirement - seasonal fruits only
- potato chips
    - special requirement - low fat and low salt
- milk
    - special requirement - lactose intolerant

**general list**
- M&M chocolate
- Coke

Thus user would have their shopping list ready (other features - voice interface integration, iot integration, collaborative, expanse management integration etc), so the app could crunch this data and prepare a plan for the user for a mall visit and gather all the items (or order from amazon, but it's about the physical experience).

When user visits the mall, the user would then open the app and follow the app instructions to visit various shops and gather the items required. The products specified on the list would be highlighted in the app and also the alternatives, user would then be able to compare the items side by side on various data dimensions - eg: reviews, ease of use, price, suggestions by the experts, etc.

Further the customer could stream their shopping session, with their family members (or whoever is associated with the requirement for the shopping item), and the collaborator would be able to check and verify their item (even compare a few on their own interface, while the person present in the shopping mall looks for other things).

Other related use-cases
- Task-rabbit, big-basket, grofers - the on demand grocery pickers and deliverers could use this solution to stream products to their premium customers

**Dependencies** 

- map of item locations by the retailers for the initial users, later when everyone would have the app this would be automatically updated
- collection of review videos and how to use videos for the products. The brands can provide these details, but later the community can have other suggestions to follow
- collection of task related sites, videos, from which user could pick any task
- understanding of the product types and the information important for that specific category (eg: calories, carbs, sugar and fat in food)
- keep the app inventory updated with the retailer's inventory

**Comment by p-raj** [comment]
# Market

- SDK
    - BlippAR - SDK, Retail, _direct competition_
    - Blue-Vision - SDK
    - eonite - SDK, Com.Vis
    - Wikitude - SDK, Education
    - Viro Media - SDK
    - 8th Wall 0 Unity SDK
    - 6D.ai
- Analytics & Visualization
    - Virtualitics
    - ObseVR.tech
    - Retail
        - InContext 
- Projector
    - Lightform
- Holograms
    - 8i
    - AEMass
- Immersive 
    - Code - primitive.io
    - Space - SpaceVR
- Hardware
    - Hololens
    - Metavision
- Misc
    - Roam Robotics (robot to check you shelves - this could be done with the cameras only)
    - Sixa.io (cloud PC like paperscape)
    - ePawn - smart physical board to convert physical games to virtual game. Cool.
    - Octi - A lot of video capture filters. AR. Cool.
    - Modeo - Customizable furniture + AR App
    - AugmenTV - Watch TV along with AP and get a lot of information in sync, overlaid on the TV
    - RealAR - see how the house would look (building) when it woule be built and decorated in AR.
    - PlayARis - Playbox for kids. Coool.
    - Summit Tech Labs - interactivity with AR
    - Menu3 - AR Food visualization
    - HCI - feel the touch of the surface in VR (3D surface, rough surface). **Interesting! How?**
    - Moatboat - speak & the VR would render the story scene & the animated movie
    - Next.io - tell stories in AR. Use app to visualize the story while reading it around the world. Eg: visualize the stories on some historic monuments.
    - Gloves - http://plexus.im/ - for VR
    - Suit for VR - Disney
    - Altar Virtual - visualize mind-map/ road-map in 3D in VR
    - TelepathEye - patented AR keyboard.
- Interactivity 
    - Thalmic Band
    - Leap Motion
    - VR Gloves
- Healthcare
    - OSSOVR - Surgery + Edu
    - Giblib - Surgery + Edu
    - Mindmaze - Neuro
- Connected Vehicle
    - White Raven
    - WayRay
- Industrial AR (collaboration)
    - Upskill
    - Daqri
    - PTC
    - Atheer
    - Scope AR
- Convert Non VR/AR devices to VR/AR
    - Occipital
- AR/VR Mapping
    - Structure.io - 3D objects scanning
    - Matterport - Home to 3D for real-estate
    - 360 degree camera
    - 3D Camera
    - Depth sensing camera
    - Obsess - (Retail shop -> Virtual Shop) (Physical shop to display the models waring dresses for better visual experience)
- Arcade & Experiences
    - Lazer tag in VR
- Print-media marketing - photo -> AR -> Try On
- Smart Mirror - Amazon Patent
- Employee Tracking - Amazon Patent
- Selling Auto-parts - Amazon Patent

# Other Random Ideas

- Network operations center (NOC) in VR - NOC operators need a lot of screens in front of them to work effectively. VR would definitely be of help there, the interaction needs to be remote free and hands on. 
- Extending the LIGHTFORM from a projector to interactive projector, where in people can select a part of the projection and keep it with them. Useful in meeting and conferences, where now people would be able to collaborate better, combine ideas and projects, interact with the presentation, add their ideas to the presentation.
- SIMS city like AR overlaid on the real city where everyone is a player. Collaborative city simulation in AR. This would help people visualize how the city would look if a skyscraper would be built, comment on the construction, discuss traffic issues, discuss city infrastructure issues, etc. Based on the design people would get a feedback on the impact it could have on their city, a world where the cities would be designed by their people, coming together to build a better city.
- Shoot a video of your place, upload and choose from various options (eg: cleaner room, spacious room, party room, etc) that you would want your room to be converted to, algorithm would then output multiple rendering for the room and suggesting new placements for all the things in the room (living space)
- Immersive Education - eg: while teaching a history lesson, take kids to the past and let them learn from the events, by visualizing instead of just listening and reading
- Social + Games + AR + GIS - chess board, puzzle by someone in the community placed on a location, other players would be able to play with the puzzle (or other games) when they are in the same position and then leave their own puzzles. A leader board.
- AR (??VR) based city wide designer shows (ref: https://www.youtube.com/watch?v=zuxA7jbJNqM) (https://www.studioroosegaarde.net/project/gates-of-light) - where the users would pay to watch the virtual city designer shows. artists would build immersive experiences over the city.
- AR app for restaurants using which the user would be able to gather more information about the food, drink (how to eat, drink, some history, calories etc) + (Menu3) visualize food on the table.
- **HR** - Internal performance review sharing platform for Candidates and HR. With every new company switch the candidate has to start over, and whatever great things he/she has done in their last company sis left behind and for an HR to gather the review feedback is a painful process (usually outsourced and usually very limited in the information captured).

# Question

- Would AR need to store all the information offline? not providing information at the speed of light in AR would be a failure, AR source needs to be in sync with the view of the user.
- What would the User Interface look like when there is no limit on the screen (size or number) - VR?
    - Voice-AI-assistant would be required to zoom into the views, data, to switch between scenes (screens), focus-in and focus-out of some information on the screen. Group, collaborate on the screens.
    - Since the screens are virtual and not physical - a flexibility would be there to merge the screens and do other complicated operations. _Eg_: merge two graphs together/ merge two data streams together/ merge multiple interfaces together and get a more powerful interface with more powers and functionality.

**Comment by p-raj** [comment]
# business canvas
<img width="1337" alt="screen shot 2018-08-16 at 4 28 06 pm" src="https://user-images.githubusercontent.com/40564263/44204712-6d2f6880-a171-11e8-949a-1f8f2e7fbf1c.png">

**Comment by p-raj** [comment]
### Very Interesting field - To be explored further
### Pending - UI
